version: '3.1'

services:
  api:
    image: traefik/whoami
    restart: unless-stopped
    deploy:
      replicas: 2
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
